Repository compiler-explorer/infra, pull requests merged in 2018-12, with the labels that each got.

#147 Add DMD nightly compiler
  update_compilers/install_d_compilers.sh
Labels: enhancement, new-compiler

#149 Support CUDA library CUB
  update_compilers/install_libraries.sh
Labels: new-libs

#146 Support for GNAT
  gcc/Dockerfile
  gcc/build/build.sh
Labels: new-compiler, new-language

#151 DMD nightly: set access rights to `+rx`
  update_compilers/install_d_compilers.sh
Labels: enhancement
