Repository compiler-explorer/infra, pull requests merged in 2021-06, with the labels that each got.

#534 Add Zig zig-args library
  bin/yaml/libraries.yaml
Labels: new-libs

#535 Add compiler for Kotlin 1.5.20
  bin/yaml/kotlin.yaml
Labels: new-compiler

#536 Add scala compiler
  bin/yaml/scala.yaml
Labels: new-compiler, new-language
