Repository compiler-explorer/infra, pull requests merged in 2021-07, with the labels that each got.

#554 Adds Haskell 8.10.5 & 9.0.1
  bin/yaml/haskell.yaml
Labels: new-compiler

#562 Add Crystal 1.1.1
  bin/yaml/crystal.yaml
Labels: new-compiler

#561 add scnlib 0.4
  bin/yaml/libraries.yaml
Labels: new-libs

#564 GCC 11.2
  bin/yaml/cpp.yaml
Labels: new-compiler

#563 Add installers for Ruby
  bin/yaml/ruby.yaml
Labels: new-language
